name: ci

on: [push]

jobs:
  execute:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      # redis:
      #   image: redis
      #   ports:
      #     - 6379:6379
      #   options: >-
      #     --health-cmd "redis-cli ping"
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Setup bundler
        run: gem install bundler
      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      # - name: Cache rubocop
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.cache/rubocop_cache
      #     key: ${{ runner.os }}-rubocop-${{ github.head_ref }}
      #     restore-keys: |
      #       ${{ runner.os }}-rubocop-
      #       ${{ runner.os }}-rubocop-${{ github.base_ref }}
      #       ${{ runner.os }}-rubocop-${{ hashFiles('**/.rubocop.yml') }}
      - name: Install gems
        run: bundle install --jobs 4
      - name: Setup Database
        run: |
          cp -v config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rails ridgepole:apply

        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      - name: Rubocop
        run: bundle exec rubocop --parallel
      - name: RSpec
        run: bundle exec rspec
